### PR TITLE
Update cost to price

### PR DESCRIPTION
**Pull request by evoactivity**
Need to use price instead of cost

### CODE REVIEW

**Comment by bcardarella** [comment]
you should just alias it instead.

**Comment by evoactivity** [comment]
Not sure what you mean about just aliasing it.

I've just installed this addon and passing `{name: 'test', cost: 100}` put an item in the cart with a cost of 0, passing `{name: 'test', price: 100}` puts an item in the cart with a cost of 100.

Further in the readme where it talks about 'Avoiding quantity incrementation' price is used instead of cost.

**Comment by bcardarella** [comment]
Apologies I misunderstood. There does seem to be an inconsistency. Let me dig in and try to recall why.

**Comment by ghost** [comment]
@bcardarella Have you figured it out yet?

**Pull request closed without merging**
